### ISSUE TITLE
Block launcher For Intel

### ISSUE THREAD

**Issue by Parju** [zhuowei/MCPELauncher#206]
New block launcher for (Intel Only) can't instal mod , can't see skin on multiplayer , and capes it looks like old block launcher :( i hope you Fix it

**Comment by zhuowei** [comment]
try again? I've released a few more betas after the first one.

**Comment by Parju** [comment]
same it doesnt works :(

**Comment by zhuowei** [comment]
@parju is Safe Mode off? Did you install MCPE from the Play Store?

**Comment by Parju** [comment]
yes safe mod off and iam install mcpe from playstore and iam try to uninstall and reinstall again but still doesnt work :( mu device zenfone 5

**Comment by Creeperface01** [comment]
My device is acer A1-840FHD and i have same problem.

**Comment by freekiller201020** [comment]
I get an error on my Nexus Player trying to ran this app. Any help?

**Comment by zhuowei** [comment]
@freekiller201020 what's the error?

**Comment by Creeperface01** [comment]
when you add Intel atom support?
