### ISSUE TITLE
Blocklauncher Crashing with my mod that worked on 0.12.3

### ISSUE THREAD

**Issue by QuintonMostert** [zhuowei/MCPELauncher#346]
My creeper buddies mod worked on 0.12.3 now it crashes when i spawn a creeper buddy i think it has something to do with the set text in the gui functions

Heres the script :
http://qbot.tk/CreepaBuddys.js

**Comment by zhuowei** [comment]
I can't download the script (gives a "Not found") error - you might want to check if you got the address right

**Comment by duggum** [comment]
If you are referring to the script at http://qbot.tk/CreepaBuddys4.js, it was riddled with errors. I went through it and fixed what my code linter found and saved it as creeper-buddy.js. I loaded it and it seems to work fine.

All files are attached including your original, my corrections, and the diff file that shows you what I fixed.

FYI, I had to add the .txt extension in order to attach the files.

[CreepaBuddys4.js.txt](https://github.com/zhuowei/MCPELauncher/files/46397/CreepaBuddys4.js.txt)

[creeper-buddy.js.txt](https://github.com/zhuowei/MCPELauncher/files/46398/creeper-buddy.js.txt)

[CreepaBuddys4.diff.txt](https://github.com/zhuowei/MCPELauncher/files/46399/CreepaBuddys4.diff.txt)

**Comment by QuintonMostert** [comment]
dude it still crashes the game when a creeper buddy is spawned and it was working fine in 0.12.3 
zhuowei please fix this :(

**Comment by duggum** [comment]
*Dude*, my version of your script.

__BlockLauncher 1.11.1-b3__
__MCPE 0.13.0__

Just sayin' ...

__1. Enter world__
![1-enter_world](https://cloud.githubusercontent.com/assets/6613807/11453915/f3abc11e-95ea-11e5-876d-baec61b8a438.png)
__2. Turn on randowm spawn__
![2-turn-on-randowm-spawn](https://cloud.githubusercontent.com/assets/6613807/11453916/f3abe054-95ea-11e5-8d95-8e22dd353f75.png)
__3. Get creeper spawners__
![3-get-creeper-spawners](https://cloud.githubusercontent.com/assets/6613807/11453918/f3acd946-95ea-11e5-8e6e-5af997aa0a07.png)
__4 Oh no, creepers__
![4-oh-no_creepers](https://cloud.githubusercontent.com/assets/6613807/11453919/f3adb0dc-95ea-11e5-8e77-a7b538be9bb5.png)
![5-more-creepers](https://cloud.githubusercontent.com/assets/6613807/11453917/f3ac5750-95ea-11e5-9eb8-6dd83c2678db.png)

**Comment by QuintonMostert** [comment]
dude the creeper buddies not the elemental creepers the pets !! you need to spawn it and name it ....
https://lh3.ggpht.com/zEYMerWUrG8igPHvOapxqP1pyhtjeLaCEgykA2zx3OGvwMdgtxOpBtI8MMbDwZz6um4=h310-rw

**Comment by duggum** [comment]
Gotcha...I didn't know about the spawning trick, I just tested the chat command spawning. I do get a crash when triggering the spawn from the egg drops.

You might want to include detailed instructions so @zhuowei knows what to do to replicate your problem.

**Comment by QuintonMostert** [comment]
Okay @zhuowei this script does not work anymore please can you fix it to replecate the problem 
Install this script : http://qbot.tk/CreepaBuddys4.js
Go into creative and in the seeds section at the bottom get the Creepa buddie spawner the chicken egg
And spawn it the game will then crash ...
This is the problem :(

**Comment by zhuowei** [comment]
I think this is the same issue as Pokedroid (anything that sets transparency to true in setTextureOffset crashes), since the mutant creeper uses transparent textures. Try 1.11.1 release, which should fix this.

**Comment by QuintonMostert** [comment]
thanks @zhuowei fixed it!
